### ISSUE TITLE
How do you configure base URL?

### ISSUE THREAD

**Issue by srid** [Compositional/reflex-servant#6]
I find the configuration to be a little complex. How do you actually specify the base URL? I'm using jsaddle-warp, so it is essentially http://localhost:3003 (3003 is the default jsaddle-warp port in reflex-dom).

**Comment by srid** [comment]
Put differently, I'm trying to figure out what you'd replace the following with:

```
myRunServantClient cfg m = error "Call servant-client or servant-client-jsaddle"
```

**Comment by roberth** [comment]
Here's an example. You can construct your own [BaseUrl](https://hackage.haskell.org/package/servant-client-core-0.13/docs/Servant-Client-Core-Internal-BaseUrl.html#t:BaseUrl) instead of using [getDefaultBaseUrl](https://github.com/Compositional/servant-client-jsaddle/blob/c7278335bb597fd75b29036a43bd870422206efa/src/Servant/Client/Internal/JSaddleXhrClient.hs#L105). You may have to add an import or two.

```
import qualified JSDOM.Generated.XMLHttpRequest as XHR
import Servant.Client.JSaddle
import Reflex.Servant.Internal.GenericClientM
import           Language.Javascript.JSaddle      (liftJSM, MonadJSM)
servantClientRunner
  :: MonadJSM m
  => ()
  -> GenericClientM a
  -> m (Either ServantError a)
servantClientRunner _ m = liftJSM $ do
  baseurl <- getDefaultBaseUrl
  let clientEnv = (mkClientEnv baseurl)
        { fixUpXhr = \xhr -> do
            XHR.setRequestHeader xhr ("X-XSRF-TOKEN" :: Text) =<< getXSRF
        }
  runGenericClientM m `runClientM` clientEnv

getCookie' :: JSM Text
getCookie' = do
  window <- eval ("window" :: Text) >>= fromJSValUnchecked
  document <- getDocument window
  getCookie document

getXSRF :: JSM Text
getXSRF = do
  cookie <- getCookie'
  let cookies = (fixup . T.breakOn "=" . T.dropWhile (== ' ')) <$> T.splitOn ";" cookie
      fixup (k, v) = (T.dropWhile (==' ') k, fromMaybe v $ T.stripPrefix "=" v)
      mtoken = lookup "XSRF-TOKEN" cookies
      token = fromMaybe "" mtoken
  return token
```

**Comment by roberth** [comment]
If you want to use more than one api, you can choose something other than `()` to distinguish between them.

**Comment by roberth** [comment]
You can use this library in more than one way. It's more of a toolbox than a framework. Having that flexibility means it exposes some details that you don't want to think about, but that you'll probably want to use at some point.

I've created a follow-up issue for a comprehensive example.

**Comment by srid** [comment]
Awesome, thanks for that code snippet!

Where is `getXSRF` coming from? I couldn't figure it out, so I changed the fixUpXhr to `return ()` value but it works.

**Comment by srid** [comment]
> If you want to use more than one api, you can choose something other than () to distinguish between them.

Eventually I want to support both jsaddle-warp and ghcjs. The former works for now, but I'll try to figure out the later. I think it would be nice if your example (#7) supported both jsaddle-warp and ghcjs. AFAIK, this is seamless with servant-reflex.

**Comment by roberth** [comment]
I've added the `getXSRF` code for completeness. You don't need to set the fixup thing, unless you want to add XSRF tokens. `return ()` is the default and it's fine when you don't need anything special.
At some point those function should become part of `servant-auth-client`, which itself should not depend on `servant-client`...
I've updated #7.
